import { useState, useEffect, useCallback } from 'react'
import { format } from 'date-fns'
import type { Semester, CourseWithSchedule, AttendanceRecord, Holiday, CourseStats, AggregateStats, DailyClass } from '@shared/types'
import { computeCourseStats, computeAggregateStats, countRemainingClasses, bunkPreview } from '../lib/calculator'
import { getOutOfRangeWarning } from '@shared/holidayEngine'

const api = window.attendGuard

// ─── useSemester ──────────────────────────────────────────────────────────────

export function useSemester() {
  const [semester, setSemester] = useState<Semester | null>(null)
  const [allSemesters, setAllSemesters] = useState<Semester[]>([])
  const [loading, setLoading] = useState(true)

  const refresh = useCallback(async () => {
    const [active, all] = await Promise.all([api.getActiveSemester(), api.listSemesters()])
    setSemester(active)
    setAllSemesters(all)
    setLoading(false)
  }, [])

  useEffect(() => { refresh() }, [refresh])

  const switchSemester = useCallback(async (id: number) => {
    await api.setActiveSemester(id)
    await refresh()
  }, [refresh])

  return { semester, allSemesters, loading, refresh, switchSemester }
}

// ─── useCourses ───────────────────────────────────────────────────────────────

export function useCourses(semesterId: number | null) {
  const [courses, setCourses] = useState<CourseWithSchedule[]>([])

  const refresh = useCallback(async () => {
    if (!semesterId) { setCourses([]); return }
    setCourses(await api.listCourses(semesterId))
  }, [semesterId])

  useEffect(() => { refresh() }, [refresh])
  return { courses, refresh }
}

// ─── useHolidays ──────────────────────────────────────────────────────────────

export function useHolidays(semesterId: number | null) {
  const [holidays, setHolidays] = useState<Holiday[]>([])

  const refresh = useCallback(async () => {
    if (!semesterId) { setHolidays([]); return }
    setHolidays(await api.listHolidays(semesterId))
  }, [semesterId])

  useEffect(() => { refresh() }, [refresh])

  const holidaySet = new Set(holidays.map(h => h.date))
  const autoCount  = holidays.filter(h => h.isAutoGenerated).length

  return { holidays, holidaySet, autoCount, refresh }
}

// ─── useAttendance ────────────────────────────────────────────────────────────

export function useAttendance(semester: Semester | null, courses: CourseWithSchedule[], holidaySet: Set<string>) {
  const [records, setRecords] = useState<AttendanceRecord[]>([])
  const [courseStats, setCourseStats] = useState<CourseStats[]>([])
  const [aggregateStats, setAggregateStats] = useState<AggregateStats | null>(null)

  const refresh = useCallback(async () => {
    if (!semester) { setRecords([]); setCourseStats([]); setAggregateStats(null); return }
    const recs = await api.getAttendanceRange(semester.id, semester.startDate, semester.endDate)
    setRecords(recs)

    const today = format(new Date(), 'yyyy-MM-dd')
    const stats = courses.map(course => {
      const threshold = course.thresholdOverride ?? semester.threshold
      const courseRecs = recs.filter(r => r.courseId === course.id)
      const attended = courseRecs.filter(r => r.status === 'attended').length
      const bunked   = courseRecs.filter(r => r.status === 'bunked').length
      const days = course.schedule.map(s => s.dayOfWeek)
      const remaining = countRemainingClasses(days, today, semester.endDate, holidaySet)

      return computeCourseStats({ courseId: course.id, courseName: course.name, courseCode: course.code, color: course.color, creditHours: course.creditHours, effectiveThreshold: threshold, attended, bunked, remaining })
    })

    setCourseStats(stats)
    setAggregateStats(computeAggregateStats(stats, semester.useCreditWeight ? 'credit-weighted' : 'simple'))
  }, [semester, courses, holidaySet])

  useEffect(() => { refresh() }, [refresh])

  const logAttendance = useCallback(async (courseId: number, date: string, status: AttendanceRecord['status']) => {
    await api.logAttendance({ courseId, date, status })
    await refresh()
  }, [refresh])

  return { records, courseStats, aggregateStats, refresh, logAttendance }
}

// ─── useDailyClasses ─────────────────────────────────────────────────────────

export function useDailyClasses(date: string, courses: CourseWithSchedule[], records: AttendanceRecord[], holidaySet: Set<string>, holidays: Holiday[], courseStats: CourseStats[]): DailyClass[] {
  const dow = new Date(date + 'T00:00:00').getDay()
  const holidayForDate = holidays.find(h => h.date === date)
  const isHolidayDate  = holidaySet.has(date)

  return courses.flatMap(course => {
    const slots = course.schedule.filter(s => s.dayOfWeek === dow)
    return slots.map(slot => {
      const record = records.find(r => r.courseId === course.id && r.date === date) ?? null
      const stats  = courseStats.find(s => s.courseId === course.id)
      const previewPct = stats ? bunkPreview(stats, 1) : null
      return { course, slot, record, isHoliday: isHolidayDate, holidayLabel: holidayForDate?.label, bunkPreviewPct: previewPct }
    })
  }).sort((a, b) => a.slot.startTime.localeCompare(b.slot.startTime))
}

// ─── useHolidayWarning ────────────────────────────────────────────────────────

export function useHolidayWarning(semester: Semester | null): string | null {
  if (!semester) return null
  return getOutOfRangeWarning(semester.startDate, semester.endDate)
}
