import { contextBridge, ipcRenderer } from 'electron'
import { electronAPI } from '@electron-toolkit/preload'
import type { AttendGuardAPI } from '../shared/types'

const attendGuard: AttendGuardAPI = {
  // Semesters
  listSemesters: ()         => ipcRenderer.invoke('semesters:list'),
  createSemester: (p)       => ipcRenderer.invoke('semesters:create', p),
  updateSemester: (p)       => ipcRenderer.invoke('semesters:update', p),
  deleteSemester: (id)      => ipcRenderer.invoke('semesters:delete', id),
  setActiveSemester: (id)   => ipcRenderer.invoke('semesters:setActive', id),
  getActiveSemester: ()     => ipcRenderer.invoke('semesters:getActive'),

  // Courses
  listCourses: (sid)        => ipcRenderer.invoke('courses:list', sid),
  createCourse: (p)         => ipcRenderer.invoke('courses:create', p),
  updateCourse: (p)         => ipcRenderer.invoke('courses:update', p),
  deleteCourse: (id)        => ipcRenderer.invoke('courses:delete', id),
  bulkCreateCourses: (cs)   => ipcRenderer.invoke('courses:bulkCreate', cs),

  // Attendance
  logAttendance: (p)                    => ipcRenderer.invoke('attendance:log', p),
  getAttendanceRange: (sid, from, to)   => ipcRenderer.invoke('attendance:getRange', sid, from, to),
  deleteAttendanceRecord: (cid, date)   => ipcRenderer.invoke('attendance:delete', cid, date),

  // Holidays
  listHolidays: (sid)                   => ipcRenderer.invoke('holidays:list', sid),
  createHoliday: (p)                    => ipcRenderer.invoke('holidays:create', p),
  deleteHoliday: (id)                   => ipcRenderer.invoke('holidays:delete', id),
  bulkCreateHolidays: (hs)              => ipcRenderer.invoke('holidays:bulkCreate', hs),
  autoGenerateHolidays: (sid)           => ipcRenderer.invoke('holidays:autoGenerate', sid),
  clearAutoGeneratedHolidays: (sid)     => ipcRenderer.invoke('holidays:clearAutoGenerated', sid),

  // Reminders
  setRemindersEnabled: (enabled)        => ipcRenderer.invoke('reminders:setEnabled', enabled),
  getRemindersEnabled: ()               => ipcRenderer.invoke('reminders:getEnabled'),
  rescheduleReminders: ()               => ipcRenderer.invoke('reminders:reschedule'),
}

if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('electron', electronAPI)
    contextBridge.exposeInMainWorld('attendGuard', attendGuard)
  } catch (error) {
    console.error(error)
  }
} else {
  // @ts-ignore
  window.electron = electronAPI
  // @ts-ignore
  window.attendGuard = attendGuard
}
