// Shared types used by both main process and renderer

export type HolidayType = 'public' | 'break' | 'university' | 'custom'
export type AttendanceStatus = 'attended' | 'bunked' | 'cancelled' | 'holiday'
export type AggregateMethod = 'simple' | 'credit-weighted'

export interface Semester {
  id: number
  name: string
  startDate: string // YYYY-MM-DD
  endDate: string // YYYY-MM-DD
  threshold: number // 0-100
  stateCode: string // 'TN', 'MH', etc.
  isActive: boolean
  useCreditWeight: boolean
}

export interface Course {
  id: number
  semesterId: number
  name: string
  code: string | null
  creditHours: number
  thresholdOverride: number | null
  color: string
}

export interface WeeklyScheduleSlot {
  id: number
  courseId: number
  dayOfWeek: number // 0=Sun, 1=Mon, ..., 6=Sat
  startTime: string // "HH:MM"
  endTime: string
}

export interface CourseWithSchedule extends Course {
  schedule: WeeklyScheduleSlot[]
}

export interface Holiday {
  id: number
  semesterId: number
  date: string // YYYY-MM-DD
  label: string
  type: HolidayType
  isAutoGenerated: boolean
}

export interface AttendanceRecord {
  id: number
  courseId: number
  date: string // YYYY-MM-DD
  status: AttendanceStatus
}

// IPC payload types
export interface CreateSemesterPayload {
  name: string
  startDate: string
  endDate: string
  threshold: number
  stateCode: string
  useCreditWeight?: boolean
}

export interface UpdateSemesterPayload extends Partial<CreateSemesterPayload> {
  id: number
}

export interface CreateCoursePayload {
  semesterId: number
  name: string
  code?: string
  creditHours?: number
  thresholdOverride?: number | null
  color?: string
  schedule?: Array<{ dayOfWeek: number; startTime: string; endTime: string }>
}

export interface LogAttendancePayload {
  courseId: number
  date: string
  status: AttendanceStatus
}

export interface CreateHolidayPayload {
  semesterId: number
  date: string
  label: string
  type: HolidayType
  isAutoGenerated?: boolean
}

// Calculation result types
export interface CourseStats {
  courseId: number
  courseName: string
  courseCode: string | null
  color: string
  threshold: number
  creditHours: number
  attendedSoFar: number
  heldSoFar: number
  remainingClasses: number
  currentPct: number | null
  bestCasePct: number
  worstCasePct: number
  safeBunksRemaining: number
  needToAttend: number // max(0, -safeBunksRemaining)
  isDataAvailable: boolean
}

export interface AggregateStats {
  currentPct: number | null
  bestCasePct: number
  worstCasePct: number
  safeBunksRemaining: number
  needToAttend: number
  method: AggregateMethod
  courseCount: number
}

export interface DailyClass {
  course: Course
  slot: WeeklyScheduleSlot
  record: AttendanceRecord | null
  isHoliday: boolean
  holidayLabel?: string
  bunkPreviewPct: number | null
}

// window.attendGuard API type
export interface AttendGuardAPI {
  listSemesters(): Promise<Semester[]>
  createSemester(payload: CreateSemesterPayload): Promise<Semester>
  updateSemester(payload: UpdateSemesterPayload): Promise<Semester>
  deleteSemester(id: number): Promise<void>
  setActiveSemester(id: number): Promise<void>
  getActiveSemester(): Promise<Semester | null>

  listCourses(semesterId: number): Promise<CourseWithSchedule[]>
  createCourse(payload: CreateCoursePayload): Promise<CourseWithSchedule>
  updateCourse(payload: Partial<CreateCoursePayload> & { id: number }): Promise<CourseWithSchedule>
  deleteCourse(id: number): Promise<void>
  bulkCreateCourses(courses: CreateCoursePayload[]): Promise<CourseWithSchedule[]>

  logAttendance(payload: LogAttendancePayload): Promise<AttendanceRecord>
  getAttendanceRange(semesterId: number, from: string, to: string): Promise<AttendanceRecord[]>
  deleteAttendanceRecord(courseId: number, date: string): Promise<void>

  listHolidays(semesterId: number): Promise<Holiday[]>
  createHoliday(payload: CreateHolidayPayload): Promise<Holiday>
  deleteHoliday(id: number): Promise<void>
  bulkCreateHolidays(holidays: CreateHolidayPayload[]): Promise<Holiday[]>
  autoGenerateHolidays(semesterId: number): Promise<Holiday[]>
  clearAutoGeneratedHolidays(semesterId: number): Promise<void>

  // Reminders
  setRemindersEnabled(enabled: boolean): Promise<{ ok: boolean }>
  getRemindersEnabled(): Promise<boolean>
  rescheduleReminders(): Promise<{ ok: boolean }>

  // Backup & Restore
  exportBackup(): Promise<string>  // returns base64-encoded SQLite bytes
  importBackup(base64: string): Promise<{ ok: boolean }>
}
