import { useState } from 'react'
import type { PageProps } from './types'
import type { Holiday, CreateHolidayPayload, HolidayType } from '@shared/types'
import { parseHolidayCSV } from '../lib/parser'

const HOLIDAY_TYPES: HolidayType[] = ['public', 'break', 'university', 'custom']

export default function HolidayPage(props: PageProps) {
  const { semester, holidays, autoCount, refreshHolidays, refreshAttendance } = props
  const [tab, setTab] = useState<'list'|'add'|'import'>('list')
  const [generating, setGenerating] = useState(false)
  const [search, setSearch] = useState('')

  if (!semester) return (
    <div className="empty-state">
      <div className="empty-state-icon">🏖️</div>
      <div className="empty-state-title">No semester active</div>
    </div>
  )

  const filtered = holidays.filter(h =>
    !search || h.label.toLowerCase().includes(search.toLowerCase()) || h.date.includes(search)
  )

  const handleRegenerate = async () => {
    setGenerating(true)
    await window.attendGuard.autoGenerateHolidays(semester.id)
    await refreshHolidays()
    setGenerating(false)
  }

  const handleDelete = async (h: Holiday) => {
    await window.attendGuard.deleteHoliday(h.id)
    await refreshHolidays()
    await refreshAttendance()
  }

  return (
    <>
      <div className="flex items-center justify-between">
        <div>
          <div className="page-title">Holidays</div>
          <div className="page-subtitle">{holidays.length} total · {autoCount} auto-generated</div>
        </div>
        <div className="flex gap-8">
          <button className="btn btn-secondary btn-sm" onClick={handleRegenerate} disabled={generating}>
            {generating ? '⏳ Generating…' : '🔄 Regenerate auto-holidays'}
          </button>
          <button className="btn btn-primary btn-sm" onClick={() => setTab('add')}>+ Add holiday</button>
        </div>
      </div>

      <div className="tabs">
        <button className={`tab${tab==='list'?' active':''}`} onClick={() => setTab('list')}>List</button>
        <button className={`tab${tab==='add'?' active':''}`} onClick={() => setTab('add')}>Add Holiday</button>
        <button className={`tab${tab==='import'?' active':''}`} onClick={() => setTab('import')}>Import CSV</button>
      </div>

      {tab === 'list' && (
        <div className="card">
          <input className="input" style={{maxWidth:320, marginBottom:16}} placeholder="Search holidays…" value={search} onChange={e => setSearch(e.target.value)} />
          {filtered.length === 0 ? (
            <div style={{textAlign:'center', padding:'32px', color:'var(--text-muted)'}}>
              {search ? 'No results.' : 'No holidays yet — click "Regenerate" to auto-generate.'}
            </div>
          ) : (
            <table className="holiday-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Label</th>
                  <th>Type</th>
                  <th>Source</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {filtered.map(h => (
                  <tr key={h.id}>
                    <td style={{fontVariantNumeric:'tabular-nums', fontWeight:600}}>{h.date}</td>
                    <td>{h.label}</td>
                    <td><span className={`type-badge ${h.type}`}>{h.type}</span></td>
                    <td>
                      {h.isAutoGenerated
                        ? <span className="auto-badge">auto</span>
                        : <span style={{fontSize:12, color:'var(--text-muted)'}}>manual</span>}
                    </td>
                    <td><button className="btn-icon" title="Delete" onClick={() => handleDelete(h)}>🗑️</button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {tab === 'add' && (
        <AddHolidayForm semesterId={semester.id} onAdded={async () => { await refreshHolidays(); setTab('list') }} />
      )}

      {tab === 'import' && (
        <ImportHolidayTab semesterId={semester.id} onImported={async () => { await refreshHolidays(); setTab('list') }} />
      )}
    </>
  )
}

// ─── Add Holiday Form ─────────────────────────────────────────────────────────

function AddHolidayForm({ semesterId, onAdded }: { semesterId: number; onAdded: () => void }) {
  const [date, setDate]   = useState('')
  const [label, setLabel] = useState('')
  const [type, setType]   = useState<HolidayType>('public')
  const [saving, setSaving] = useState(false)
  const [error, setError]  = useState('')

  const save = async () => {
    if (!date || !label.trim()) { setError('Date and label are required'); return }
    setSaving(true); setError('')
    await window.attendGuard.createHoliday({ semesterId, date, label: label.trim(), type })
    setSaving(false)
    onAdded()
  }

  return (
    <div className="card" style={{display:'flex', flexDirection:'column', gap:16, maxWidth:480}}>
      <div className="page-title" style={{fontSize:16}}>Add Holiday</div>
      {error && <div style={{color:'var(--red)', fontSize:13}}>{error}</div>}
      <div className="form-group">
        <label className="form-label">Date</label>
        <input className="input" type="date" value={date} onChange={e => setDate(e.target.value)} />
      </div>
      <div className="form-group">
        <label className="form-label">Label</label>
        <input className="input" value={label} onChange={e => setLabel(e.target.value)} placeholder="e.g. Diwali" />
      </div>
      <div className="form-group">
        <label className="form-label">Type</label>
        <select className="select" value={type} onChange={e => setType(e.target.value as HolidayType)}>
          {HOLIDAY_TYPES.map(t => <option key={t} value={t}>{t.charAt(0).toUpperCase() + t.slice(1)}</option>)}
        </select>
      </div>
      <div className="flex gap-12">
        <button className="btn btn-primary" onClick={save} disabled={saving}>
          {saving ? '⏳ Saving…' : '✅ Add Holiday'}
        </button>
      </div>
    </div>
  )
}

// ─── Import Tab ───────────────────────────────────────────────────────────────

function ImportHolidayTab({ semesterId, onImported }: { semesterId: number; onImported: () => void }) {
  const [errors, setErrors]   = useState<Array<{row:number; column:string; value:string; reason:string}>>([])
  const [preview, setPreview] = useState<Omit<CreateHolidayPayload, 'semesterId'>[]>([])
  const [status, setStatus]   = useState<'idle'|'loading'|'done'>('idle')

  const handleFile = async (file: File) => {
    setStatus('loading'); setErrors([]); setPreview([])
    const result = parseHolidayCSV(await file.text())
    setErrors(result.errors); setPreview(result.holidays); setStatus('idle')
  }

  const doImport = async () => {
    setStatus('loading')
    await window.attendGuard.bulkCreateHolidays(preview.map(h => ({ ...h, semesterId })))
    setStatus('done'); setPreview([]); setErrors([])
    onImported()
  }

  return (
    <div className="card" style={{display:'flex', flexDirection:'column', gap:16}}>
      <div
        className="dropzone"
        onClick={() => document.getElementById('holiday-file-input')?.click()}
        onDragOver={e => e.preventDefault()}
        onDrop={e => { e.preventDefault(); const f=e.dataTransfer.files[0]; if(f) handleFile(f) }}
      >
        <div className="dropzone-icon">📄</div>
        <div className="dropzone-text">Drop a CSV file or click to browse</div>
        <div className="dropzone-hint">Columns: Date (YYYY-MM-DD), Label, Type (public/break/university/custom)</div>
        <input id="holiday-file-input" type="file" accept=".csv" style={{display:'none'}} onChange={e => { const f=e.target.files?.[0]; if(f) handleFile(f); e.target.value='' }} />
      </div>

      {errors.length > 0 && (
        <div className="error-list">
          <div className="error-list-title">⚠️ {errors.length} errors</div>
          {errors.map((e,i) => <div key={i} className="error-item"><span className="error-row-num">Row {e.row}:</span> {e.reason}</div>)}
        </div>
      )}

      {preview.length > 0 && !errors.length && (
        <div>
          <div style={{fontWeight:600, marginBottom:12}}>Preview: {preview.length} holidays</div>
          {preview.slice(0,5).map((h,i) => <div key={i} style={{fontSize:13, padding:'6px 10px', background:'var(--bg-elevated)', borderRadius:6, marginBottom:4}}>{h.date} — {h.label} ({h.type})</div>)}
          {preview.length > 5 && <div style={{fontSize:12, color:'var(--text-muted)'}}>…and {preview.length - 5} more</div>}
          <div className="flex gap-12 mt-16">
            <button className="btn btn-primary" onClick={doImport} disabled={status==='loading'}>
              {status==='loading' ? '⏳ Importing…' : `Import ${preview.length} holidays`}
            </button>
            <button className="btn btn-secondary" onClick={() => setPreview([])}>Cancel</button>
          </div>
        </div>
      )}
    </div>
  )
}
