import { ipcMain } from 'electron'
import { z } from 'zod'
import { getDb } from '../database'
import { generateHolidays } from '../../shared/holidayEngine'
import type { Holiday, CreateHolidayPayload } from '../../shared/types'

const HolidaySchema = z.object({
  semesterId: z.number().int(),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  label: z.string().min(1),
  type: z.enum(['public', 'break', 'university', 'custom']),
  isAutoGenerated: z.boolean().optional().default(false)
})

function r2h(r: Record<string, unknown>): Holiday {
  return {
    id: r.id as number,
    semesterId: r.semester_id as number,
    date: r.date as string,
    label: r.label as string,
    type: r.type as Holiday['type'],
    isAutoGenerated: (r.is_auto_generated as number) === 1
  }
}

export function registerHolidayHandlers(): void {
  ipcMain.handle('holidays:list', (_e, semesterId: number) => {
    return (getDb().prepare('SELECT * FROM holidays WHERE semester_id = ? ORDER BY date').all(semesterId) as Record<string, unknown>[]).map(r2h)
  })

  ipcMain.handle('holidays:create', (_e, payload: CreateHolidayPayload) => {
    const db = getDb()
    const p = HolidaySchema.parse(payload)
    const res = db.prepare(
      'INSERT OR IGNORE INTO holidays (semester_id, date, label, type, is_auto_generated) VALUES (?, ?, ?, ?, ?)'
    ).run(p.semesterId, p.date, p.label, p.type, p.isAutoGenerated ? 1 : 0)
    if (res.changes === 0) {
      // already exists — update label/type
      db.prepare('UPDATE holidays SET label = ?, type = ? WHERE semester_id = ? AND date = ? AND label = ?').run(p.label, p.type, p.semesterId, p.date, p.label)
    }
    return r2h(db.prepare('SELECT * FROM holidays WHERE semester_id = ? AND date = ? AND label = ?').get(p.semesterId, p.date, p.label) as Record<string, unknown>)
  })

  ipcMain.handle('holidays:delete', (_e, id: number) => {
    getDb().prepare('DELETE FROM holidays WHERE id = ?').run(id)
  })

  ipcMain.handle('holidays:bulkCreate', (_e, holidays: CreateHolidayPayload[]) => {
    const db = getDb()
    const results: Holiday[] = []
    const ins = db.prepare('INSERT OR IGNORE INTO holidays (semester_id, date, label, type, is_auto_generated) VALUES (?, ?, ?, ?, ?)')
    db.transaction(() => {
      for (const h of holidays) {
        const p = HolidaySchema.parse(h)
        const res = ins.run(p.semesterId, p.date, p.label, p.type, p.isAutoGenerated ? 1 : 0)
        if (res.changes > 0) {
          results.push(r2h(db.prepare('SELECT * FROM holidays WHERE id = ?').get(res.lastInsertRowid) as Record<string, unknown>))
        }
      }
    })()
    return results
  })

  ipcMain.handle('holidays:autoGenerate', (_e, semesterId: number) => {
    const db = getDb()
    const sem = db.prepare('SELECT * FROM semesters WHERE id = ?').get(semesterId) as Record<string, unknown> | undefined
    if (!sem) throw new Error('Semester not found')

    // Detect Saturday classes
    const scheduledDays = new Set(
      (db.prepare(`SELECT DISTINCT ws.day_of_week FROM weekly_schedule ws JOIN courses c ON c.id = ws.course_id WHERE c.semester_id = ?`).all(semesterId) as Array<{ day_of_week: number }>).map(r => r.day_of_week)
    )

    const generated = generateHolidays({
      startDate: sem.start_date as string,
      endDate: sem.end_date as string,
      stateCode: sem.state_code as string,
      includeSaturdays: !scheduledDays.has(6)
    })

    // Clear old auto-generated, then insert fresh
    db.prepare('DELETE FROM holidays WHERE semester_id = ? AND is_auto_generated = 1').run(semesterId)

    const results: Holiday[] = []
    const ins = db.prepare('INSERT OR IGNORE INTO holidays (semester_id, date, label, type, is_auto_generated) VALUES (?, ?, ?, ?, 1)')
    db.transaction(() => {
      for (const h of generated) {
        const res = ins.run(semesterId, h.date, h.label, h.type)
        if (res.changes > 0) results.push(r2h(db.prepare('SELECT * FROM holidays WHERE id = ?').get(res.lastInsertRowid) as Record<string, unknown>))
      }
    })()
    return results
  })

  ipcMain.handle('holidays:clearAutoGenerated', (_e, semesterId: number) => {
    getDb().prepare('DELETE FROM holidays WHERE semester_id = ? AND is_auto_generated = 1').run(semesterId)
  })
}
